swiftmailer:
  #url: '%env(MAILER_URL)%'
  spool: { type: "memory" }
  username: "admin@initi-tech.com"
  password: "1n1D@stone1n1"
  host: "ssl0.ovh.net"
  port: 465
  transport: smtp
  encryption: ssl
  auth-mode: login
  stream_options:
    ssl:
      allow_self_signed: true
      verify_peer: false
      verify_peer_name: false
