vich_uploader:
  db_driver: orm

  mappings:
    featured_images:
      uri_prefix: "/images/logement"
      upload_destination: "%kernel.project_dir%/../images/logement"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
